export const CHAPTERS = [
  { value: 'all', label: 'כל הפרקים', label_en: 'All Chapters' },

  // BOLOGNIA TEXTBOOK CHAPTERS (Complete List)
  { value: 'anatomy-pathophysiology', label: 'אנטומיה ופתופיזיולוגיה', label_en: 'Anatomy and Pathophysiology' },
  { value: 'skin-development', label: 'התפתחות ותחזוקת העור', label_en: 'Skin Development and Maintenance' },
  { value: 'molecular-biology', label: 'ביולוגיה מולקולרית', label_en: 'Molecular Biology' },
  { value: 'genetics', label: 'עקרונות גנטיקה', label_en: 'Basic Principles of Genetics' },
  { value: 'neurophysiology', label: 'נוירופיזיולוגיה עורית', label_en: 'Cutaneous Neurophysiology' },
  { value: 'pruritus', label: 'גרד ודיסאסתזיה', label_en: 'Pruritus and Dysesthesia' },
  { value: 'psychocutaneous', label: 'מחלות פסיכוקוטאניות', label_en: 'Psychocutaneous Diseases' },
  { value: 'psoriasis', label: 'פסוריאזיס', label_en: 'Psoriasis' },
  { value: 'papulosquamous', label: 'הפרעות פפולוסקוואמיות אחרות', label_en: 'Other Papulosquamous Disorders' },
  { value: 'erythroderma', label: 'אריתרודרמה', label_en: 'Erythroderma' },
  { value: 'lichen-planus', label: 'ליכן פלנוס והפרעות ליכנואידיות', label_en: 'Lichen Planus and Lichenoid Dermatoses' },
  { value: 'atopic-dermatitis', label: 'דרמטיטיס אטופית', label_en: 'Atopic Dermatitis' },
  { value: 'other-eczema', label: 'התפרצויות אקזמטיות אחרות', label_en: 'Other eczematous eruptions' },
  { value: 'allergic-contact', label: 'דרמטיטיס ממגע אלרגית', label_en: 'Allergic Contact Dermatitis' },
  { value: 'irritant-contact', label: 'דרמטיטיס ממגע מגרה', label_en: 'Irritant Contact Dermatitis' },
  { value: 'occupational', label: 'דרמטוזות תעסוקתיות', label_en: 'Occupational Dermatoses' },
  { value: 'plants', label: 'דרמטוזות עקב צמחים', label_en: 'Dermatoses Due to Plants' },
  { value: 'urticaria', label: 'אורטיקריה ואנגיואדמה', label_en: 'Urticaria and Angioedema' },
  { value: 'figurate-erythemas', label: 'אריתמות פיגורטיות', label_en: 'Figurate Erythemas' },
  { value: 'erythema-multiforme', label: 'אריתמה מולטיפורמה, תסמונת סטיבנס-ג\'ונסון', label_en: 'Erythema Multiforme, Stevens–Johnson Syndrome' },
  { value: 'drug-reactions', label: 'תגובות לתרופות', label_en: 'Drug Reactions' },
  { value: 'purpura', label: 'פורפורה: מנגנונים ואבחנה מבדלת', label_en: 'Purpura: Mechanisms and Differential Diagnosis' },
  { value: 'microvascular', label: 'ביטויים עוריים של מחלות מיקרווסקולריות', label_en: 'Cutaneous Manifestations of Microvascular' },
  { value: 'vasculitis', label: 'וסקוליטיס עורית', label_en: 'Cutaneous Vasculitis' },
  { value: 'neutrophilic', label: 'דרמטוזות נויטרופיליות', label_en: 'Neutrophilic Dermatoses' },
  { value: 'eosinophil', label: 'דרמטוזות הקשורות באאוזינופילים', label_en: 'Eosinophil-Associated Dermatoses' },
  { value: 'pregnancy', label: 'דרמטוזות הריון', label_en: 'Pregnancy Dermatoses' },
  { value: 'basement-membrane', label: 'ביולוגיה של קרום הבסיס', label_en: 'The Biology of the Basement Membrane' },
  { value: 'pemphigus', label: 'פמפיגוס', label_en: 'Pemphigus' },
  { value: 'pemphigoid', label: 'קבוצת הפמפיגואיד', label_en: 'pemphigoid group' },
  { value: 'dermatitis-herpetiformis', label: 'דרמטיטיס הרפטיפורמיס ו-Linear IgA Bullous', label_en: 'Dermatitis Herpetiformis and Linear IgA Bullous' },
  { value: 'epidermolysis-bullosa', label: 'אפידרמוליזיס בולוסה', label_en: 'Epidermolysis Bullosa' },
  { value: 'other-bullous', label: 'מחלות וזיקולובולוסיות אחרות', label_en: 'Other Vesiculobullous Diseases' },
  { value: 'newborn-vesiculopustular', label: 'הפרעות וזיקולופוסטולריות ואירוזיביות ביילודים', label_en: 'Vesiculopustular and Erosive Disorders in Newborns' },
  { value: 'sweat-glands-structure', label: 'מבנה ותפקוד של בלוטות אקריניות ואפוקריניות', label_en: 'Structure and Function of Eccrine, Apocrine, and' },
  { value: 'acne', label: 'אקנה וולגריס', label_en: 'Acne Vulgaris' },
  { value: 'rosacea', label: 'רוזאצאה והפרעות קשורות', label_en: 'Rosacea and Related Disorders' },
  { value: 'folliculitis', label: 'פוליקוליטיס, Follicular Occlusion Tetrad ואחרות', label_en: 'Folliculitis, Follicular Occlusion Tetrad, and Other' },
  { value: 'sweat-gland-diseases', label: 'מחלות של בלוטות זיעה אקריניות ואפוקריניות', label_en: 'Diseases of the Eccrine and Apocrine Sweat Glands' },
  { value: 'autoantibodies', label: 'נוגדנים עצמיים במחלות רקמת חיבור אוטואימוניות', label_en: 'Autoantibodies Encountered in Patients with Autoimmune Connective Tissue Diseases' },
  { value: 'lupus', label: 'לופוס אריתמטוזוס', label_en: 'Lupus Erythematosus' },
  { value: 'dermatomyositis', label: 'דרמטומיוזיטיס', label_en: 'Dermatomyositis' },
  { value: 'scleroderma', label: 'סקלרודרמה והפרעות קשורות', label_en: 'Systemic Sclerosis (Scleroderma) and Related Disorders' },
  { value: 'morphea', label: 'מורפאה וליכן סקלרוזוס', label_en: 'Morphea and Lichen Sclerosus' },
  { value: 'rheumatologic', label: 'הפרעות ראומטולוגיות ומחלות דלקתיות אוטו-דלקתיות אחרות', label_en: 'Other Rheumatologic Disorders and Autoinflammatory Diseases' },
  { value: 'mucinoses', label: 'מוצינוזות', label_en: 'Mucinoses' },
  { value: 'amyloidosis', label: 'עמילואידוזיס', label_en: 'Amyloidosis' },
  { value: 'deposition', label: 'מחלות שקיעה', label_en: 'Deposition Diseases' },
  { value: 'porphyria', label: 'פורפיריה', label_en: 'Porphyria' },
  { value: 'calcifying', label: 'הפרעות הסתיידות והתאבנות של העור', label_en: 'Calcifying and Ossifying Disorders of the Skin' },
  { value: 'nutritional', label: 'מחלות תזונתיות', label_en: 'Nutritional Diseases' },
  { value: 'gvhd', label: 'מחלת השתל נגד המאכסן', label_en: 'Graft-versus-Host Disease' },
  { value: 'systemic-manifestations', label: 'ביטויים דרמטולוגיים במטופלים עם מחלות מערכתיות', label_en: 'Dermatologic Manifestations in Patients with Systemic' },
  { value: 'immunology', label: 'אימונולוגיה', label_en: 'Immunology' },
  { value: 'genetic-basis', label: 'בסיס גנטי של מחלות עוריות', label_en: 'Genetic Basis of Cutaneous Diseases' },
  { value: 'keratinocytes', label: 'ביולוגיה של קרטינוציטים', label_en: 'Biology of Keratinocytes' },
  { value: 'ichthyoses', label: 'איכתיוזות, אריתרוקרטודרמות והפרעות קשורות', label_en: 'Ichthyoses, Erythrokeratodermas, and Related Disorders' },
  { value: 'palmoplantar-keratodermas', label: 'קרטודרמות כפות ידיים וכפות רגליים', label_en: 'Palmoplantar Keratodermas' },
  { value: 'darier-hailey', label: 'מחלת דריה ומחלת הייליי-הייליי', label_en: 'Darier Disease and Hailey–Hailey Disease' },
  { value: 'immunodeficiencies', label: 'חוסרים חיסוניים ראשוניים', label_en: 'Primary Immunodeficiencies' },
  { value: 'neurofibromatosis', label: 'נוירופיברומטוזיס וקומפלקס טוברוס סקלרוזיס', label_en: 'Neurofibromatosis and Tuberous Sclerosis Complex' },
  { value: 'mosaicism', label: 'מוזאיציזם ונגעים לינאריים', label_en: 'Mosaicism and Linear Lesions' },
  { value: 'other-genodermatoses', label: 'גנודרמטוזות אחרות', label_en: 'Other Genodermatoses' },
  { value: 'developmental-anomalies', label: 'אנומליות התפתחותיות', label_en: 'Developmental Anomalies' },
  { value: 'melanocyte-biology', label: 'ביולוגיה של מלנוציטים', label_en: 'Melanocyte Biology' },
  { value: 'vitiligo', label: 'ויטיליגו והפרעות היפופיגמנטציה אחרות', label_en: 'Vitiligo and Other Disorders of Hypopigmentation' },
  { value: 'hyperpigmentation', label: 'הפרעות היפרפיגמנטציה', label_en: 'Disorders of Hyperpigmentation' },
  { value: 'hair-nail-biology', label: 'ביולוגיה של שיער וציפורניים', label_en: 'Biology of Hair and Nails' },
  { value: 'alopecias', label: 'אלופציות', label_en: 'Alopecias' },
  { value: 'hypertrichosis', label: 'היפרטריכוזיס והירסוטיזם', label_en: 'Hypertrichosis and Hirsutism' },
  { value: 'nail-disorders', label: 'הפרעות ציפורניים', label_en: 'Nail Disorders' },
  { value: 'oral', label: 'מחלות פה', label_en: 'Oral Diseases' },
  { value: 'anogenital', label: 'מחלות אנוגניטליות (שאינן מחלות מין)', label_en: 'Anogenital (Non-venereal) Diseases' },
  { value: 'bacterial', label: 'מחלות חיידקיות', label_en: 'Bacterial Diseases' },
  { value: 'mycobacterial', label: 'זיהומים מיקובקטריאליים', label_en: 'Mycobacterial Infections' },
  { value: 'rickettsial', label: 'מחלות ריקציאליות', label_en: 'Rickettsial Diseases' },
  { value: 'fungal', label: 'מחלות פטרייתיות', label_en: 'Fungal Diseases' },
  { value: 'hiv', label: 'ביטויים עוריים של זיהום HIV', label_en: 'Cutaneous Manifestations of HIV Infection' },
  { value: 'hpv', label: 'נגיפי פפילומה אנושיים', label_en: 'Human Papillomaviruses' },
  { value: 'herpes', label: 'נגיפי הרפס אנושיים', label_en: 'Human Herpesviruses' },
  { value: 'other-viral', label: 'מחלות ויראליות אחרות', label_en: 'Other Viral Diseases' },
  { value: 'sti', label: 'זיהומים המועברים במגע מיני', label_en: 'Sexually Transmitted Infections' },
  { value: 'protozoa-worms', label: 'פרוטוזואה ותולעים', label_en: 'Protozoa and Worms' },
  { value: 'infestations', label: 'נגיעות טפיליות', label_en: 'Infestations' },
  { value: 'bites-stings', label: 'עקיצות ועקיצות', label_en: 'Bites and Stings' },
  { value: 'uv-radiation', label: 'קרינת אולטרה-סגול', label_en: 'Ultraviolet Radiation' },
  { value: 'photodermatologic', label: 'הפרעות פוטודרמטולוגיות', label_en: 'Photodermatologic Disorders' },
  { value: 'environmental-sports', label: 'מחלות עור סביבתיות וקשורות לספורט', label_en: 'Environmental and Sports-Related Skin Diseases' },
  { value: 'substance-use', label: 'סימנים של הפרעת שימוש בחומרים', label_en: 'Signs of Substance Use Disorder' },
  { value: 'abuse-signs', label: 'סימני התעללות בעור', label_en: 'Skin Signs of Abuse' },
  { value: 'histiocytoses', label: 'היסטיוציטוזות', label_en: 'Histiocytoses' },
  { value: 'xanthomas', label: 'קסנתומות', label_en: 'Xanthomas' },
  { value: 'granulomas', label: 'גרנולומות לא-זיהומיות', label_en: 'Non-infectious Granulomas' },
  { value: 'foreign-body', label: 'תגובות גוף זר', label_en: 'Foreign Body Reactions' },
  { value: 'extracellular-matrix', label: 'ביולוגיה של המטריקס החוץ-תאי', label_en: 'Biology of the Extracellular Matrix' },
  { value: 'perforating', label: 'מחלות מחוררות', label_en: 'Perforating Diseases' },
  { value: 'connective-tissue-heritable', label: 'הפרעות תורשתיות של רקמת חיבור', label_en: 'Heritable Disorders of Connective Tissue' },
  { value: 'dermal-hypertrophies', label: 'היפרטרופיות דרמליות', label_en: 'Dermal Hypertrophies' },
  { value: 'atrophies', label: 'אטרופיות של רקמת חיבור', label_en: 'Atrophies of Connective Tissue' },
  { value: 'panniculitis', label: 'פאניקוליטיס', label_en: 'Panniculitis' },
  { value: 'lipodystrophies', label: 'ליפודיסטרופיות', label_en: 'Lipodystrophies' },
  { value: 'vascular-biology', label: 'ביולוגיה וסקולרית', label_en: 'Vascular Biology' },
  { value: 'hemangiomas', label: 'המנגיומות של תינוקות', label_en: 'Infantile Hemangiomas' },
  { value: 'vascular-malformations', label: 'מומי כלי דם', label_en: 'Vascular Malformations' },
  { value: 'ulcers', label: 'כיבים', label_en: 'Ulcers' },
  { value: 'other-vascular', label: 'הפרעות וסקולריות אחרות', label_en: 'Other Vascular Disorders' },
  { value: 'tumor-biology', label: 'עקרונות ביולוגיה של גידולי עור', label_en: 'Principles of Cutaneous Tumor Biology' },
  { value: 'ak-bcc-scc', label: 'קרטוזיס אקטינית, קרצינומת תאי בסיס וקרצינומת תאי קשקש', label_en: 'Actinic Keratosis, Basal Cell Carcinoma, and Squamous' },
  { value: 'benign-epidermal', label: 'גידולים אפידרמליים שפירים והפרעות התפשטות', label_en: 'Benign Epidermal Tumors and Proliferations' },
  { value: 'cysts', label: 'ציסטות', label_en: 'Cysts' },
  { value: 'adnexal', label: 'נאופלזמות אדנקסליות', label_en: 'Adnexal Neoplasms' },
  { value: 'benign-melanocytic', label: 'נאופלזמות מלנוציטיות שפירות ונגעים מלנוטיים', label_en: 'Benign Melanocytic Neoplasms and Melanotic Lesions' },
  { value: 'melanoma', label: 'מלנומה', label_en: 'Melanoma' },
  { value: 'vascular-neoplasms', label: 'נאופלזמות וסקולריות והתפשטויות דמויות נאופלסטיות', label_en: 'Vascular Neoplasms and Neoplastic-Like Proliferations' },
  { value: 'neural', label: 'נאופלזמות נוירליות ונוירואנדוקריניות', label_en: 'Neural and Neuroendocrine Neoplasms' },
  { value: 'fibroblastic', label: 'נאופלזמות פיברובלסטיות, מיופיברובלסטיות ו"פיברוהיסטיוציטיות"', label_en: 'Fibroblastic, Myofibroblastic and "Fibrohistiocytic"' },
  { value: 'smooth-muscle-adipose', label: 'נאופלזמות של שריר חלק, רקמת שומן וסחוס', label_en: 'Smooth Muscle, Adipose, and Cartilage Neoplasms' },
  { value: 'mastocytosis', label: 'מסטוציטוזיס', label_en: 'Mastocytosis' },
  { value: 'b-cell-lymphoma', label: 'לימפומות תאי B של העור', label_en: 'B Cell Lymphomas of the Skin' },
  { value: 'ctcl', label: 'לימפומת תאי T עורית', label_en: 'Cutaneous T Cell Lymphoma' },
  { value: 'lymphoproliferative', label: 'הפרעות לימפופרוליפרטיביות ומיאלופרוליפרטיביות אחרות', label_en: 'Other Lymphoproliferative and Myeloproliferative' },
  { value: 'metastases', label: 'גרורות עוריות', label_en: 'Cutaneous Metastases' },
  { value: 'public-health', label: 'בריאות הציבור ודרמטולוגיה', label_en: 'Public Health and Dermatology' },
  { value: 'skin-barrier', label: 'מחסום העור', label_en: 'Skin Barrier' },
  { value: 'drug-delivery', label: 'מסירת תרופות טרנסדרמלית וטופיקלית', label_en: 'Transdermal and Topical Drug Delivery' },
  { value: 'glucocorticoids', label: 'גלוקוקורטיקואידים', label_en: 'Glucocorticoids' },
  { value: 'retinoids', label: 'רטינואידים', label_en: 'Retinoids' },
  { value: 'antimicrobials', label: 'תרופות אנטימיקרוביאליות', label_en: 'Antimicrobial Drugs' },
  { value: 'immunomodulators', label: 'אימונומודולטורים מערכתיים', label_en: 'Systemic Immunomodulators' },
  { value: 'topical-meds', label: 'תרופות טופיקליות אחרות', label_en: 'Other Topical Medications' },
  { value: 'systemic-drugs', label: 'תרופות מערכתיות אחרות', label_en: 'Other Systemic Drugs' },
  { value: 'drug-interactions', label: 'אינטראקציות תרופתיות', label_en: 'Drug Interactions' },
  { value: 'sunscreens', label: 'קרמי הגנה והגנה פוטואקטיבית', label_en: 'Sunscreens and Photoprotection' },
  { value: 'complementary-medicine', label: 'רפואה משלימה ואלטרנטיבית', label_en: 'Complementary and Alternative Medicine' },
  { value: 'uv-therapy', label: 'טיפול באולטרה-סגול', label_en: 'Ultraviolet Therapy' },
  { value: 'photodynamic', label: 'טיפול פוטודינמי', label_en: 'Photodynamic Therapy' },
  { value: 'lasers-energy', label: 'לייזרים וטכנולוגיות מבוססות אנרגיה', label_en: 'Lasers and Other Energy-Based Technologies' },
  { value: 'lasers-therapies', label: 'לייזרים וטיפולים מבוססי אנרגיה אחרים', label_en: 'Lasers and Other Energy-Based Therapies' },
  { value: 'cryosurgery', label: 'קריוכירורגיה', label_en: 'Cryosurgery' },
  { value: 'radiotherapy', label: 'רדיותרפיה', label_en: 'Radiotherapy' },
  { value: 'electrosurgery', label: 'אלקטרוכירורגיה', label_en: 'Electrosurgery' },
  { value: 'wound-healing', label: 'ביולוגיה של ריפוי פצעים', label_en: 'Biology of Wound Healing' },
  { value: 'surgical-anatomy', label: 'אנטומיה כירורגית של הראש והצוואר', label_en: 'Surgical Anatomy of the Head and Neck' },
  { value: 'anesthesia', label: 'הרדמה', label_en: 'Anesthesia' },
  { value: 'closure-materials', label: 'חומרי סגירת פצעים וכלים', label_en: 'Wound Closure Materials and Instruments' },
  { value: 'dressings', label: 'חבישות', label_en: 'Dressings' },
  { value: 'biopsy-excisions', label: 'טכניקות ביופסיה וכריתות בסיסיות', label_en: 'Biopsy Techniques and Basic Excisions' },
  { value: 'flaps', label: 'דשים', label_en: 'Flaps' },
  { value: 'grafts', label: 'השתלות', label_en: 'Grafts' },
  { value: 'nail-surgery', label: 'כירורגיית ציפורניים', label_en: 'Nail Surgery' },
  { value: 'mohs', label: 'כירורגיית מוהס מיקרוגרפית', label_en: 'Mohs Micrographic Surgery' },
  { value: 'surgical-complications', label: 'סיבוכים כירורגיים ואופטימיזציה של תוצאות', label_en: 'Surgical Complications and Optimizing Outcomes' },
  { value: 'beauty-aging', label: 'הערכת יופי והזדקנות הפנים', label_en: 'Evaluation of Beauty and the Aging Face' },
  { value: 'cosmetics', label: 'קוסמטיקה וקוסמצוטיקלס', label_en: 'Cosmetics and Cosmeceuticals' },
  { value: 'resurfacing', label: 'החלקת עור כימית ומכנית', label_en: 'Chemical and Mechanical Skin Resurfacing' },
  { value: 'phlebology', label: 'פלבולוגיה וטיפול בוורידי רגליים', label_en: 'Phlebology and Treatment of Leg Veins' },
  { value: 'body-contouring', label: 'עיצוב הגוף: שאיבת שומן ולא-פולשנית', label_en: 'Body Contouring: Liposuction and Non-invasive' },
  { value: 'hair-restoration', label: 'שיקום שיער', label_en: 'Hair Restoration' },
  { value: 'fillers', label: 'הזרקת חומרי מילוי לרקמות רכות', label_en: 'Injectable Soft Tissue Augmentation' },
  { value: 'botox', label: 'בוטולינום טוקסין', label_en: 'Botulinum Toxin' },
]
