export const CHAPTERS = [
  { value: 'all', label: 'כל הפרקים', label_en: 'All Chapters', number: null },
  { value: 'other', label: 'אחר', label_en: 'Other', number: 0 },

  // BOLOGNIA TEXTBOOK CHAPTERS (Complete List with Chapter Numbers)
  { value: 'anatomy-pathophysiology', label: 'אנטומיה ופתופיזיולוגיה', label_en: 'Anatomy and Pathophysiology', number: 1 },
  { value: 'skin-development', label: 'התפתחות ותחזוקת העור', label_en: 'Skin Development and Maintenance', number: 2 },
  { value: 'molecular-biology', label: 'ביולוגיה מולקולרית', label_en: 'Molecular Biology', number: 3 },
  { value: 'genetics', label: 'עקרונות גנטיקה', label_en: 'Basic Principles of Genetics', number: 4 },
  { value: 'neurophysiology', label: 'נוירופיזיולוגיה עורית', label_en: 'Cutaneous Neurophysiology', number: 5 },
  { value: 'pruritus', label: 'גרד ודיסאסתזיה', label_en: 'Pruritus and Dysesthesia', number: 6 },
  { value: 'psychocutaneous', label: 'מחלות פסיכוקוטאניות', label_en: 'Psychocutaneous Diseases', number: 7 },
  { value: 'psoriasis', label: 'פסוריאזיס', label_en: 'Psoriasis', number: 8 },
  { value: 'papulosquamous', label: 'הפרעות פפולוסקוואמיות אחרות', label_en: 'Other Papulosquamous Disorders', number: 9 },
  { value: 'erythroderma', label: 'אריתרודרמה', label_en: 'Erythroderma', number: 10 },
  { value: 'lichen-planus', label: 'ליכן פלנוס והפרעות ליכנואידיות', label_en: 'Lichen Planus and Lichenoid Dermatoses', number: 11 },
  { value: 'atopic-dermatitis', label: 'דרמטיטיס אטופית', label_en: 'Atopic Dermatitis', number: 12 },
  { value: 'other-eczema', label: 'התפרצויות אקזמטיות אחרות', label_en: 'Other eczematous eruptions', number: 13 },
  { value: 'allergic-contact', label: 'דרמטיטיס ממגע אלרגית', label_en: 'Allergic Contact Dermatitis', number: 14 },
  { value: 'irritant-contact', label: 'דרמטיטיס ממגע מגרה', label_en: 'Irritant Contact Dermatitis', number: 15 },
  { value: 'occupational', label: 'דרמטוזות תעסוקתיות', label_en: 'Occupational Dermatoses', number: 16 },
  { value: 'plants', label: 'דרמטוזות עקב צמחים', label_en: 'Dermatoses Due to Plants', number: 17 },
  { value: 'urticaria', label: 'אורטיקריה ואנגיואדמה', label_en: 'Urticaria and Angioedema', number: 18 },
  { value: 'figurate-erythemas', label: 'אריתמות פיגורטיות', label_en: 'Figurate Erythemas', number: 19 },
  { value: 'erythema-multiforme', label: 'אריתמה מולטיפורמה, תסמונת סטיבנס-ג\'ונסון', label_en: 'Erythema Multiforme, Stevens–Johnson Syndrome', number: 20 },
  { value: 'drug-reactions', label: 'תגובות לתרופות', label_en: 'Drug Reactions', number: 21 },
  { value: 'purpura', label: 'פורפורה: מנגנונים ואבחנה מבדלת', label_en: 'Purpura: Mechanisms and Differential Diagnosis', number: 22 },
  { value: 'microvascular', label: 'ביטויים עוריים של מחלות מיקרווסקולריות', label_en: 'Cutaneous Manifestations of Microvascular', number: 23 },
  { value: 'vasculitis', label: 'וסקוליטיס עורית', label_en: 'Cutaneous Vasculitis', number: 24 },
  { value: 'neutrophilic', label: 'דרמטוזות נויטרופיליות', label_en: 'Neutrophilic Dermatoses', number: 25 },
  { value: 'eosinophil', label: 'דרמטוזות הקשורות באאוזינופילים', label_en: 'Eosinophil-Associated Dermatoses', number: 26 },
  { value: 'pregnancy', label: 'דרמטוזות הריון', label_en: 'Pregnancy Dermatoses', number: 27 },
  { value: 'basement-membrane', label: 'ביולוגיה של קרום הבסיס', label_en: 'The Biology of the Basement Membrane', number: 28 },
  { value: 'pemphigus', label: 'פמפיגוס', label_en: 'Pemphigus', number: 29 },
  { value: 'pemphigoid', label: 'קבוצת הפמפיגואיד', label_en: 'pemphigoid group', number: 30 },
  { value: 'dermatitis-herpetiformis', label: 'דרמטיטיס הרפטיפורמיס ו-Linear IgA Bullous', label_en: 'Dermatitis Herpetiformis and Linear IgA Bullous', number: 31 },
  { value: 'epidermolysis-bullosa', label: 'אפידרמוליזיס בולוסה', label_en: 'Epidermolysis Bullosa', number: 32 },
  { value: 'other-bullous', label: 'מחלות וזיקולובולוסיות אחרות', label_en: 'Other Vesiculobullous Diseases', number: 33 },
  { value: 'newborn-vesiculopustular', label: 'הפרעות וזיקולופוסטולריות ואירוזיביות ביילודים', label_en: 'Vesiculopustular and Erosive Disorders in Newborns', number: 34 },
  { value: 'sweat-glands-structure', label: 'מבנה ותפקוד של בלוטות אקריניות ואפוקריניות', label_en: 'Structure and Function of Eccrine, Apocrine, and', number: 35 },
  { value: 'acne', label: 'אקנה וולגריס', label_en: 'Acne Vulgaris', number: 36 },
  { value: 'rosacea', label: 'רוזאצאה והפרעות קשורות', label_en: 'Rosacea and Related Disorders', number: 37 },
  { value: 'folliculitis', label: 'פוליקוליטיס, Follicular Occlusion Tetrad ואחרות', label_en: 'Folliculitis, Follicular Occlusion Tetrad, and Other', number: 38 },
  { value: 'sweat-gland-diseases', label: 'מחלות של בלוטות זיעה אקריניות ואפוקריניות', label_en: 'Diseases of the Eccrine and Apocrine Sweat Glands', number: 39 },
  { value: 'autoantibodies', label: 'נוגדנים עצמיים במחלות רקמת חיבור אוטואימוניות', label_en: 'Autoantibodies Encountered in Patients with Autoimmune Connective Tissue Diseases', number: 40 },
  { value: 'lupus', label: 'לופוס אריתמטוזוס', label_en: 'Lupus Erythematosus', number: 41 },
  { value: 'dermatomyositis', label: 'דרמטומיוזיטיס', label_en: 'Dermatomyositis', number: 42 },
  { value: 'scleroderma', label: 'סקלרודרמה והפרעות קשורות', label_en: 'Systemic Sclerosis (Scleroderma) and Related Disorders', number: 43 },
  { value: 'morphea', label: 'מורפאה וליכן סקלרוזוס', label_en: 'Morphea and Lichen Sclerosus', number: 44 },
  { value: 'rheumatologic', label: 'הפרעות ראומטולוגיות ומחלות דלקתיות אוטו-דלקתיות אחרות', label_en: 'Other Rheumatologic Disorders and Autoinflammatory Diseases', number: 45 },
  { value: 'mucinoses', label: 'מוצינוזות', label_en: 'Mucinoses', number: 46 },
  { value: 'amyloidosis', label: 'עמילואידוזיס', label_en: 'Amyloidosis', number: 47 },
  { value: 'deposition', label: 'מחלות שקיעה', label_en: 'Deposition Diseases', number: 48 },
  { value: 'porphyria', label: 'פורפיריה', label_en: 'Porphyria', number: 49 },
  { value: 'calcifying', label: 'הפרעות הסתיידות והתאבנות של העור', label_en: 'Calcifying and Ossifying Disorders of the Skin', number: 50 },
  { value: 'nutritional', label: 'מחלות תזונתיות', label_en: 'Nutritional Diseases', number: 51 },
  { value: 'gvhd', label: 'מחלת השתל נגד המאכסן', label_en: 'Graft-versus-Host Disease', number: 52 },
  { value: 'systemic-manifestations', label: 'ביטויים דרמטולוגיים במטופלים עם מחלות מערכתיות', label_en: 'Dermatologic Manifestations in Patients with Systemic', number: 53 },
  { value: 'immunology', label: 'אימונולוגיה', label_en: 'Immunology', number: 54 },
  { value: 'genetic-basis', label: 'בסיס גנטי של מחלות עוריות', label_en: 'Genetic Basis of Cutaneous Diseases', number: 55 },
  { value: 'keratinocytes', label: 'ביולוגיה של קרטינוציטים', label_en: 'Biology of Keratinocytes', number: 56 },
  { value: 'ichthyoses', label: 'איכתיוזות, אריתרוקרטודרמות והפרעות קשורות', label_en: 'Ichthyoses, Erythrokeratodermas, and Related Disorders', number: 57 },
  { value: 'palmoplantar-keratodermas', label: 'קרטודרמות כפות ידיים וכפות רגליים', label_en: 'Palmoplantar Keratodermas', number: 58 },
  { value: 'darier-hailey', label: 'מחלת דריה ומחלת הייליי-הייליי', label_en: 'Darier Disease and Hailey–Hailey Disease', number: 59 },
  { value: 'immunodeficiencies', label: 'חוסרים חיסוניים ראשוניים', label_en: 'Primary Immunodeficiencies', number: 60 },
  { value: 'neurofibromatosis', label: 'נוירופיברומטוזיס וקומפלקס טוברוס סקלרוזיס', label_en: 'Neurofibromatosis and Tuberous Sclerosis Complex', number: 61 },
  { value: 'mosaicism', label: 'מוזאיציזם ונגעים לינאריים', label_en: 'Mosaicism and Linear Lesions', number: 62 },
  { value: 'other-genodermatoses', label: 'גנודרמטוזות אחרות', label_en: 'Other Genodermatoses', number: 63 },
  { value: 'developmental-anomalies', label: 'אנומליות התפתחותיות', label_en: 'Developmental Anomalies', number: 64 },
  { value: 'melanocyte-biology', label: 'ביולוגיה של מלנוציטים', label_en: 'Melanocyte Biology', number: 65 },
  { value: 'vitiligo', label: 'ויטיליגו והפרעות היפופיגמנטציה אחרות', label_en: 'Vitiligo and Other Disorders of Hypopigmentation', number: 66 },
  { value: 'hyperpigmentation', label: 'הפרעות היפרפיגמנטציה', label_en: 'Disorders of Hyperpigmentation', number: 67 },
  { value: 'hair-nail-biology', label: 'ביולוגיה של שיער וציפורניים', label_en: 'Biology of Hair and Nails', number: 68 },
  { value: 'alopecias', label: 'אלופציות', label_en: 'Alopecias', number: 69 },
  { value: 'hypertrichosis', label: 'היפרטריכוזיס והירסוטיזם', label_en: 'Hypertrichosis and Hirsutism', number: 70 },
  { value: 'nail-disorders', label: 'הפרעות ציפורניים', label_en: 'Nail Disorders', number: 71 },
  { value: 'oral', label: 'מחלות פה', label_en: 'Oral Diseases', number: 72 },
  { value: 'anogenital', label: 'מחלות אנוגניטליות (שאינן מחלות מין)', label_en: 'Anogenital (Non-venereal) Diseases', number: 73 },
  { value: 'bacterial', label: 'מחלות חיידקיות', label_en: 'Bacterial Diseases', number: 74 },
  { value: 'mycobacterial', label: 'זיהומים מיקובקטריאליים', label_en: 'Mycobacterial Infections', number: 75 },
  { value: 'rickettsial', label: 'מחלות ריקציאליות', label_en: 'Rickettsial Diseases', number: 76 },
  { value: 'fungal', label: 'מחלות פטרייתיות', label_en: 'Fungal Diseases', number: 77 },
  { value: 'hiv', label: 'ביטויים עוריים של זיהום HIV', label_en: 'Cutaneous Manifestations of HIV Infection', number: 78 },
  { value: 'hpv', label: 'נגיפי פפילומה אנושיים', label_en: 'Human Papillomaviruses', number: 79 },
  { value: 'herpes', label: 'נגיפי הרפס אנושיים', label_en: 'Human Herpesviruses', number: 80 },
  { value: 'other-viral', label: 'מחלות ויראליות אחרות', label_en: 'Other Viral Diseases', number: 81 },
  { value: 'sti', label: 'זיהומים המועברים במגע מיני', label_en: 'Sexually Transmitted Infections', number: 82 },
  { value: 'protozoa-worms', label: 'פרוטוזואה ותולעים', label_en: 'Protozoa and Worms', number: 83 },
  { value: 'infestations', label: 'נגיעות טפיליות', label_en: 'Infestations', number: 84 },
  { value: 'bites-stings', label: 'עקיצות ועקיצות', label_en: 'Bites and Stings', number: 85 },
  { value: 'uv-radiation', label: 'קרינת אולטרה-סגול', label_en: 'Ultraviolet Radiation', number: 86 },
  { value: 'photodermatologic', label: 'הפרעות פוטודרמטולוגיות', label_en: 'Photodermatologic Disorders', number: 87 },
  { value: 'environmental-sports', label: 'מחלות עור סביבתיות וקשורות לספורט', label_en: 'Environmental and Sports-Related Skin Diseases', number: 88 },
  { value: 'substance-use', label: 'סימנים של הפרעת שימוש בחומרים', label_en: 'Signs of Substance Use Disorder', number: 89 },
  { value: 'abuse-signs', label: 'סימני התעללות בעור', label_en: 'Skin Signs of Abuse', number: 90 },
  { value: 'histiocytoses', label: 'היסטיוציטוזות', label_en: 'Histiocytoses', number: 91 },
  { value: 'xanthomas', label: 'קסנתומות', label_en: 'Xanthomas', number: 92 },
  { value: 'granulomas', label: 'גרנולומות לא-זיהומיות', label_en: 'Non-infectious Granulomas', number: 93 },
  { value: 'foreign-body', label: 'תגובות גוף זר', label_en: 'Foreign Body Reactions', number: 94 },
  { value: 'extracellular-matrix', label: 'ביולוגיה של המטריקס החוץ-תאי', label_en: 'Biology of the Extracellular Matrix', number: 95 },
  { value: 'perforating', label: 'מחלות מחוררות', label_en: 'Perforating Diseases', number: 96 },
  { value: 'connective-tissue-heritable', label: 'הפרעות תורשתיות של רקמת חיבור', label_en: 'Heritable Disorders of Connective Tissue', number: 97 },
  { value: 'dermal-hypertrophies', label: 'היפרטרופיות דרמליות', label_en: 'Dermal Hypertrophies', number: 98 },
  { value: 'atrophies', label: 'אטרופיות של רקמת חיבור', label_en: 'Atrophies of Connective Tissue', number: 99 },
  { value: 'panniculitis', label: 'פאניקוליטיס', label_en: 'Panniculitis', number: 100 },
  { value: 'lipodystrophies', label: 'ליפודיסטרופיות', label_en: 'Lipodystrophies', number: 101 },
  { value: 'vascular-biology', label: 'ביולוגיה וסקולרית', label_en: 'Vascular Biology', number: 102 },
  { value: 'hemangiomas', label: 'המנגיומות של תינוקות', label_en: 'Infantile Hemangiomas', number: 103 },
  { value: 'vascular-malformations', label: 'מומי כלי דם', label_en: 'Vascular Malformations', number: 104 },
  { value: 'ulcers', label: 'כיבים', label_en: 'Ulcers', number: 105 },
  { value: 'other-vascular', label: 'הפרעות וסקולריות אחרות', label_en: 'Other Vascular Disorders', number: 106 },
  { value: 'tumor-biology', label: 'עקרונות ביולוגיה של גידולי עור', label_en: 'Principles of Cutaneous Tumor Biology', number: 107 },
  { value: 'ak-bcc-scc', label: 'קרטוזיס אקטינית, קרצינומת תאי בסיס וקרצינומת תאי קשקש', label_en: 'Actinic Keratosis, Basal Cell Carcinoma, and Squamous', number: 108 },
  { value: 'benign-epidermal', label: 'גידולים אפידרמליים שפירים והפרעות התפשטות', label_en: 'Benign Epidermal Tumors and Proliferations', number: 109 },
  { value: 'cysts', label: 'ציסטות', label_en: 'Cysts', number: 110 },
  { value: 'adnexal', label: 'נאופלזמות אדנקסליות', label_en: 'Adnexal Neoplasms', number: 111 },
  { value: 'benign-melanocytic', label: 'נאופלזמות מלנוציטיות שפירות ונגעים מלנוטיים', label_en: 'Benign Melanocytic Neoplasms and Melanotic Lesions', number: 112 },
  { value: 'melanoma', label: 'מלנומה', label_en: 'Melanoma', number: 113 },
  { value: 'vascular-neoplasms', label: 'נאופלזמות וסקולריות והתפשטויות דמויות נאופלסטיות', label_en: 'Vascular Neoplasms and Neoplastic-Like Proliferations', number: 114 },
  { value: 'neural', label: 'נאופלזמות נוירליות ונוירואנדוקריניות', label_en: 'Neural and Neuroendocrine Neoplasms', number: 115 },
  { value: 'fibroblastic', label: 'נאופלזמות פיברובלסטיות, מיופיברובלסטיות ו"פיברוהיסטיוציטיות"', label_en: 'Fibroblastic, Myofibroblastic and "Fibrohistiocytic"', number: 116 },
  { value: 'smooth-muscle-adipose', label: 'נאופלזמות של שריר חלק, רקמת שומן וסחוס', label_en: 'Smooth Muscle, Adipose, and Cartilage Neoplasms', number: 117 },
  { value: 'mastocytosis', label: 'מסטוציטוזיס', label_en: 'Mastocytosis', number: 118 },
  { value: 'b-cell-lymphoma', label: 'לימפומות תאי B של העור', label_en: 'B Cell Lymphomas of the Skin', number: 119 },
  { value: 'ctcl', label: 'לימפומת תאי T עורית', label_en: 'Cutaneous T Cell Lymphoma', number: 120 },
  { value: 'lymphoproliferative', label: 'הפרעות לימפופרוליפרטיביות ומיאלופרוליפרטיביות אחרות', label_en: 'Other Lymphoproliferative and Myeloproliferative', number: 121 },
  { value: 'metastases', label: 'גרורות עוריות', label_en: 'Cutaneous Metastases', number: 122 },
  { value: 'public-health', label: 'בריאות הציבור ודרמטולוגיה', label_en: 'Public Health and Dermatology', number: 123 },
  { value: 'skin-barrier', label: 'מחסום העור', label_en: 'Skin Barrier', number: 124 },
  { value: 'drug-delivery', label: 'מסירת תרופות טרנסדרמלית וטופיקלית', label_en: 'Transdermal and Topical Drug Delivery', number: 124 },
  { value: 'glucocorticoids', label: 'גלוקוקורטיקואידים', label_en: 'Glucocorticoids', number: 125 },
  { value: 'retinoids', label: 'רטינואידים', label_en: 'Retinoids', number: 126 },
  { value: 'antimicrobials', label: 'תרופות אנטימיקרוביאליות', label_en: 'Antimicrobial Drugs', number: 127 },
  { value: 'immunomodulators', label: 'אימונומודולטורים מערכתיים', label_en: 'Systemic Immunomodulators', number: 128 },
  { value: 'topical-meds', label: 'תרופות טופיקליות אחרות', label_en: 'Other Topical Medications', number: 129 },
  { value: 'systemic-drugs', label: 'תרופות מערכתיות אחרות', label_en: 'Other Systemic Drugs', number: 130 },
  { value: 'drug-interactions', label: 'אינטראקציות תרופתיות', label_en: 'Drug Interactions', number: 131 },
  { value: 'sunscreens', label: 'קרמי הגנה והגנה פוטואקטיבית', label_en: 'Sunscreens and Photoprotection', number: 132 },
  { value: 'complementary-medicine', label: 'רפואה משלימה ואלטרנטיבית', label_en: 'Complementary and Alternative Medicine', number: 133 },
  { value: 'uv-therapy', label: 'טיפול באולטרה-סגול', label_en: 'Ultraviolet Therapy', number: 134 },
  { value: 'photodynamic', label: 'טיפול פוטודינמי', label_en: 'Photodynamic Therapy', number: 135 },
  { value: 'lasers-energy', label: 'לייזרים וטכנולוגיות מבוססות אנרגיה', label_en: 'Lasers and Other Energy-Based Technologies', number: 136 },
  { value: 'lasers-therapies', label: 'לייזרים וטיפולים מבוססי אנרגיה אחרים', label_en: 'Lasers and Other Energy-Based Therapies', number: 137 },
  { value: 'cryosurgery', label: 'קריוכירורגיה', label_en: 'Cryosurgery', number: 138 },
  { value: 'radiotherapy', label: 'רדיותרפיה', label_en: 'Radiotherapy', number: 139 },
  { value: 'electrosurgery', label: 'אלקטרוכירורגיה', label_en: 'Electrosurgery', number: 140 },
  { value: 'wound-healing', label: 'ביולוגיה של ריפוי פצעים', label_en: 'Biology of Wound Healing', number: 141 },
  { value: 'surgical-anatomy', label: 'אנטומיה כירורגית של הראש והצוואר', label_en: 'Surgical Anatomy of the Head and Neck', number: 142 },
  { value: 'anesthesia', label: 'הרדמה', label_en: 'Anesthesia', number: 143 },
  { value: 'closure-materials', label: 'חומרי סגירת פצעים וכלים', label_en: 'Wound Closure Materials and Instruments', number: 144 },
  { value: 'dressings', label: 'חבישות', label_en: 'Dressings', number: 145 },
  { value: 'biopsy-excisions', label: 'טכניקות ביופסיה וכריתות בסיסיות', label_en: 'Biopsy Techniques and Basic Excisions', number: 146 },
  { value: 'flaps', label: 'דשים', label_en: 'Flaps', number: 147 },
  { value: 'grafts', label: 'השתלות', label_en: 'Grafts', number: 148 },
  { value: 'nail-surgery', label: 'כירורגיית ציפורניים', label_en: 'Nail Surgery', number: 149 },
  { value: 'mohs', label: 'כירורגיית מוהס מיקרוגרפית', label_en: 'Mohs Micrographic Surgery', number: 150 },
  { value: 'surgical-complications', label: 'סיבוכים כירורגיים ואופטימיזציה של תוצאות', label_en: 'Surgical Complications and Optimizing Outcomes', number: 151 },
  { value: 'beauty-aging', label: 'הערכת יופי והזדקנות הפנים', label_en: 'Evaluation of Beauty and the Aging Face', number: 152 },
  { value: 'cosmetics', label: 'קוסמטיקה וקוסמצוטיקלס', label_en: 'Cosmetics and Cosmeceuticals', number: 153 },
  { value: 'resurfacing', label: 'החלקת עור כימית ומכנית', label_en: 'Chemical and Mechanical Skin Resurfacing', number: 154 },
  { value: 'phlebology', label: 'פלבולוגיה וטיפול בוורידי רגליים', label_en: 'Phlebology and Treatment of Leg Veins', number: 155 },
  { value: 'body-contouring', label: 'עיצוב הגוף: שאיבת שומן ולא-פולשנית', label_en: 'Body Contouring: Liposuction and Non-invasive', number: 156 },
  { value: 'hair-restoration', label: 'שיקום שיער', label_en: 'Hair Restoration', number: 157 },
  { value: 'fillers', label: 'הזרקת חומרי מילוי לרקמות רכות', label_en: 'Injectable Soft Tissue Augmentation', number: 158 },
  { value: 'botox', label: 'בוטולינום טוקסין', label_en: 'Botulinum Toxin', number: 159 },
]
